name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node-version: '20.x'

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm pack --dry-run

  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --accept=200,403,429
            --exclude "http://localhost*"
            --exclude "https://localhost*"
            --exclude "https://opencollective.com/*"
            "**/*.html" "**/*.md" "**/*.txt" "**/*.json"
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  all-ci-checks-pass:
    needs:
      - link-checker
      - node-tests
      - build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}
        run: |
          echo "One or more job cancelled, failed, or skipped" && exit 1
      - run: |
          echo '## :heavy_check_mark: All continuous integration checks pass' >> $GITHUB_STEP_SUMMARY
